apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-application.fullname" . }}
  labels:
    {{- include "k8s-application.labels" . | nindent 4 }}
spec:
  replicas: {{ default .Values.replicaCount 1 }}
  selector:
    matchLabels:
      {{- include "k8s-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-application.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
         {{- end }}