name: Publish container to GitHub registry
on:
 push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  AZ_GROUP: FREE
  AZ_CLUSTER: k8s-spring-cluster

jobs:
  publish-container:
    name: Publish container to GitHub registry
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3.14.1
        with:
           distribution: 'temurin'
           java-version: 21
           cache: 'gradle'
      - name: Build jar file
        run: |
         chmod +x ./gradlew
         ./gradlew bootJar
      - name: Get app version
        id: application_version 
        continue-on-error: true
        run: |
         VERSION=$(./gradlew -q printVersion)
         echo "version=$VERSION" | tee -a $GITHUB_OUTPUT
      - name: Print
        run: echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.application_version.outputs.version }}"
        
      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with: 
          context: .
          push: true
          platforms: linux/arm64
          tags:  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.application_version.outputs.version }}
      - name: Print image
        run: echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.application_version.outputs.version }}
      
      - name: Login to Azure
        uses: Azure/login@v2.3.0
        with:
         creds: ${{ secrets.AZURE_CREDS }}
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az aks get-credentials --resource-group ${{ env.AZ_GROUP }} --name ${{ env.AZ_CLUSTER }}
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4
        id: install
      - uses: azure/aks-set-context@v4
        with:
         resource-group: ${{ env.AZ_GROUP }}
         cluster-name: ${{ env.AZ_CLUSTER }}
      - name: Get K8s context 
        run: kubectl config current-context
      - uses: azure/setup-helm@v4.3.0
        with:
         id: install
      - name: Deploy with helm
        run: |
         which helm
         helm version
         
       
   
   
   
