name: Publish container to GitHub registry
on:
 push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-container:
    name: Publish container to GitHub registry
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3.14.1
        with:
           distribution: 'temurin'
           java-version: 21
           cache: 'gradle'
      - name: Build jar file
        run: |
         chmod +x ./gradlew
         ./gradlew bootJar
      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} 
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with: 
          context: .
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Print tags
        run: echo ${{ toJson(steps.meta.outputs.tags) }}
      - name: Login to Azure
        uses: Azure/login@v2.3.0
        with:
         creds: ${{ secrets.AZURE_CREDS }}
     
   
   
   
