name: release.yml
on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, labeled]

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: contains(join(fromJSON(toJson(github.event.pull_request.labels)).*.name, ','), 'Release')
    steps:
      - run: echo '${{ toJSON(github) }}'